"""empty message

Revision ID: 1c95c82c3591
Revises: 
Create Date: 2025-09-27 14:21:19.766110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c95c82c3591'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coffeelog_coffee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roasting_facility', sa.String(), nullable=False),
    sa.Column('coffee_name', sa.String(), nullable=False),
    sa.Column('size_g', sa.Integer(), nullable=False),
    sa.Column('roast_date', sa.Date(), nullable=True),
    sa.Column('open_date', sa.Date(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('country_of_origin', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coffeelog_coffee'))
    )
    op.create_table('coffeelog_cup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('coffee_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['coffee_id'], ['coffeelog_coffee.id'], name=op.f('fk_coffeelog_cup_coffee_id_coffeelog_coffee')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coffeelog_cup'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coffeelog_cup')
    op.drop_table('coffeelog_coffee')
    # ### end Alembic commands ###
